### ISSUE TITLE
Incompatibility with `typescript-eslint`, "You have used a rule which requires parserServices to be generated"

### ISSUE THREAD

**Issue by alexrecuenco** [ota-meshi/eslint-plugin-astro#393]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.4.0

### What version of `eslint-plugin-astro` are you using?

^1.2.0

### What did you do?

<details>
<summary>Configuration</summary>

I tried using eslint 8, which is the maximum compatible version with typescript-eslint 7, and I also tried using 9.4 with the 8.0.0 alpha version of typescript-eslint 

```json
    "@typescript-eslint/parser": "^7.12.0",
    "eslint": "^9.4.0",
    "eslint-plugin-astro": "^1.2.0",
    "typescript-eslint": "^8.0.0-alpha.28"
```

```json
  "devDependencies": {
    "@typescript-eslint/parser": "^7.12.0",
    "eslint": "^8.57.0",
    "eslint-plugin-astro": "^1.2.0",
    "typescript-eslint": "^7.12.0"
  }
```

```js
import eslintPluginAstro from 'eslint-plugin-astro';
import tseslint from "typescript-eslint";

export default [
  ...tseslint.configs.recommended,
  // First issue, eslintPluginAstro MUST be defined after, since it overrides the typescript parser
  ...eslintPluginAstro.configs['flat/all'],
  {
    rules: {
      // If this is turned on, it fails.
      '@typescript-eslint/await-thenable': "off",
      '@typescript-eslint/await-thenable': "error",
      // Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];
```
</details>

It reports correctly here if I turn `'@typescript-eslint/await-thenable'` off, but if I turn it on, it fails with 

```
Oops! Something went wrong! :(

ESLint: 9.4.0

Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: undefined
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting /Users/alexrecuenco/Desktop/delete/eslint.config.mjs
    at throwError (/Users/alexrecuenco/Desktop/delete/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:40:11)
    at getParserServices (/Users/alexrecuenco/Desktop/delete/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:26:9)
    at create (/Users/alexrecuenco/Desktop/delete/node_modules/typescript-eslint/node_modules/@typescript-eslint/eslint-plugin/dist/rules/await-thenable.js:46:55)
    at Object.create (/Users/alexrecuenco/Desktop/delete/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:32:20)
    at createRuleListeners (/Users/alexrecuenco/Desktop/delete/node_modules/eslint/lib/linter/linter.js:973:21)
    at /Users/alexrecuenco/Desktop/delete/node_modules/eslint/lib/linter/linter.js:1099:84
    at Array.forEach (<anonymous>)
    at runRules (/Users/alexrecuenco/Desktop/delete/node_modules/eslint/lib/linter/linter.js:1031:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/Users/alexrecuenco/Desktop/delete/node_modules/eslint/lib/linter/linter.js:1880:31)
    at Linter._verifyWithFlatConfigArray (/Users/alexrecuenco/Desktop/delete/node_modules/eslint/lib/linter/linter.js:2016:21)
```

```astro
---
const a: any = 1;
const b = 0;
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
    <title>Astro</title>
  </head>
  <body>
    <h1>Astro {a}</h1>
  </body>
</html>
```

### What did you expect to happen?

It doesn't throw an error when I use `@typescript-eslint/await-thenable` 
It doesn't throw an error when I use `@typescript-eslint/no-explicit-any`

### What actually happened?

It **throws an error** when I turn `@typescript-eslint/await-thenable` on
It doesn't throw an error when I turn `@typescript-eslint/no-explicit-any` on.

### Link to Minimal Reproducible Example

https://github.com/alexrecuenco/astro-eslint-plugin-report-issue

### Additional comments

I've tried to go into the internals and add a project settings, I've tried to add my own typescript parser setting... but I think this is something that needs to be fix at the root, or at least to give some guidance in how to work with typescript-eslint together with the eslint-plugin-astro

**Comment by Hdoc1509** [comment]
Hi, try to add the following to your `eslint.config.js`:

```diff
export default [
  ...configs, // <- tseslint and astro configs
+ {
+   languageOptions: {
+     parserOptions: {
+       project: true,
+       tsConfigRootDir: impot.meta.dirname,
+   },
+ },
  {
    rules: { ... },
  },
]
```

You can check it at https://typescript-eslint.io/getting-started/typed-linting

**Comment by alexrecuenco** [comment]
Yeap! That was it, thank you.

I was using those same settings, but using them with `files:` and `ignores:` and it kept giving different issues.
