### ISSUE TITLE
Not working with typescriptEslint.configs.recommendedTypeChecked

### ISSUE THREAD

**Issue by drwpow-figma** [ota-meshi/eslint-plugin-astro#447]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.14.0

### What version of `eslint-plugin-astro` are you using?

1.3.1

### What did you do?

When using [typescript-eslint’s typechecked preset](https://typescript-eslint.io/getting-started/typed-linting), linting throws an error and doesn’t run.

```js
// eslint.config.js
import eslint from "@eslint/js";
import eslintPluginAstro from "eslint-plugin-astro";
import tseslint from "typescript-eslint";

export default tseslint.config(
  eslint.configs.recommended,

  // this fails:
  ...tseslint.configs.recommendedTypeChecked,

  // this works, if above is commented, and this is used instead:
  // ...tseslint.configs.recommended,

  ...eslintPluginAstro.configs.recommended
);
```

### What did you expect to happen?

Lint run completes

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 9.14.0

Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires type information, but don't have parserOptions set to generate type information for this file. See https://typescript-eslint.io/getting-started/typed-linting for enabling linting with type information.
Parser: astro-eslint-parser
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting /astro-eslint-repro/src/components/Card.astro
    at throwError (/astro-eslint-repro/node_modules/.pnpm/@typescript-eslint+utils@8.13.0_eslint@9.14.0_typescript@5.6.3/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:38:11)
    at getParserServices (/astro-eslint-repro/node_modules/.pnpm/@typescript-eslint+utils@8.13.0_eslint@9.14.0_typescript@5.6.3/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:27:9)
    at create (/astro-eslint-repro/node_modules/.pnpm/@typescript-eslint+eslint-plugin@8.13.0_@typescript-eslint+parser@8.13.0_eslint@9.14.0_typescript@5.6.3/node_modules/@typescript-eslint/eslint-plugin/dist/rules/await-thenable.js:49:55)
    at Object.create (/astro-eslint-repro/node_modules/.pnpm/@typescript-eslint+utils@8.13.0_eslint@9.14.0_typescript@5.6.3/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/astro-eslint-repro/node_modules/.pnpm/eslint@9.14.0/node_modules/eslint/lib/linter/linter.js:943:21)
    at /astro-eslint-repro/node_modules/.pnpm/eslint@9.14.0/node_modules/eslint/lib/linter/linter.js:1068:84
    at Array.forEach (<anonymous>)
    at runRules (/astro-eslint-repro/node_modules/.pnpm/eslint@9.14.0/node_modules/eslint/lib/linter/linter.js:999:34)
    at #flatVerifyWithoutProcessors (/astro-eslint-repro/node_modules/.pnpm/eslint@9.14.0/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/astro-eslint-repro/node_modules/.pnpm/eslint@9.14.0/node_modules/eslint/lib/linter/linter.js:1992:49)
```

### Link to Minimal Reproducible Example

https://github.com/drwpow-figma/astro-eslint-repro

### Additional comments

Thanks for a great plugin! ❤️

**Comment by drwpow** [comment]
Ah @ghchaosfae I did see that error as well! But I didn’t know if that was moving “forward” or “backward” so-to-speak. Wanted to find the most minimal issue, and work from there. But to your point, likely a different error happens when we move past the first step, if we determine that’s the right fix.

**Comment by drwpow** [comment]
@ghchaosfae great find! Yes that’s a good workaround, but would love to keep using `projectService` if possible, because like you said that’s what ESLint recommends (and seems to be the “happy path” going forward)

**Comment by martinburger** [comment]
I ran into the same problem when I started using the [eslint-config-love](https://github.com/mightyiam/eslint-config-love) package.

It includes `projectService: true` [in the shared configuration](https://github.com/mightyiam/eslint-config-love/blob/314923d50a98eb2f775d612cdafcc529b01a4b0d/src/index.ts#L13), which causes similar problems.

My current workaround is to programmatically delete `languageOptions` in `eslint.config.mjs`, which seems more like a hack than a workaround:

```
import configLove from 'eslint-config-love'
delete configLove.languageOptions
```

**Comment by in-in** [comment]
The problem is still here. 
![25004193218](https://github.com/user-attachments/assets/663032b5-22d2-48e5-88cc-86e4484c0b9f)

Only now the parser tries to use the old `project` option itself instead of the new one, but it still doesn't work in my case.

```sh
`astro-eslint-parser` does not support the `projectService` option, it will parse it as `project: true` instead.
```

**Comment by AndreaPontrandolfo** [comment]
Did you guys try the [extrafileextensions option](https://typescript-eslint.io/packages/parser/#extrafileextensions) ?

Also [related](https://typescript-eslint.io/troubleshooting/typed-linting/performance/#changes-to-extrafileextensions-with-projectservice).

**Comment by lostfictions** [comment]
I hit the same issue -- I'm still seeing `Parsing error: Type expected` when I try to lint files.

It looks like if you've got a configuration that sets `projectService` upstream in the config chain, `eslint-plugin-astro` will error out. To make things work, `projectService` needs to be unset, and `project` needs to be set explicitly. What's more, it seems like this needs to happen in two different places:

- The parser for `astro` files (which invokes `typescript-eslint` as a sub-parser)
- The parser for "virtual" script files.

See this plugin's [`base.ts`](https://github.com/ota-meshi/eslint-plugin-astro/blob/4f4110d713b97bb85e24afe610b1d92c62d8b7f4/src/configs/flat/base.ts) config for details.

Here's what fixed it for me:

```ts
import config from "my-custom-eslint-config-with-typechecked-rules";
import astro from "eslint-plugin-astro";

const ts = "typescript-eslint/parser";

export default [
  ...config,
  ...astro.configs.recommended.map((c) => {
    const opts = c.languageOptions;
    const baseParser = opts?.parser?.meta?.name;
    const subParser = opts?.parserOptions?.parser?.meta?.name;

    if (opts && (baseParser === ts || subParser === ts)) {
      opts.parserOptions = {
        ...opts.parserOptions,
        projectService: false,
        project: true,
      };
    }

    return c;
  }),
];
```

**Comment by Daniel15** [comment]
> I have a simple config workaround for the moment, just don't use typed rules for astro files:

@jasikpark This is a great idea. I also had to disable the typed rules for `'**/*.astro/*.ts'` too, so that linting for `<script>` tags works properly too. The `client-side-ts` processor extracts them into virtual files under that path.

Here's what I've got up with so far, that seems to work
```ts
import {includeIgnoreFile} from '@eslint/compat';
import astro from 'eslint-plugin-astro';
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import json from '@eslint/json';
import css from '@eslint/css';
import {defineConfig, globalIgnores} from 'eslint/config';
import prettier from 'eslint-config-prettier';
import {resolve} from 'node:path';

export default defineConfig(
  includeIgnoreFile(resolve(import.meta.dirname, '.gitignore')),
  // Un-ignore virtual TypeScript files from <script> tags in Astro components.
  globalIgnores(['!.astro/**/*.ts']),
  css.configs.recommended,
  json.configs.recommended,
  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        // Required to enable type-checked rules.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  astro.configs.recommended,
  // `client-side-ts` extracts <script> tags from Astro components.
  {
    files: ['**/*.astro'],
    processor: astro.processors['client-side-ts'],
  },

  // Disable type-checked rules in Astro components.
  // https://github.com/ota-meshi/eslint-plugin-astro/issues/447
  {
    files: ['**/*.astro', '**/*.astro/*.ts'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: false,
      },
    },
  },
  prettier,
);
```

> The only part that doesn't seem to work is client <script> tags nested in components.

@lostfictions  You need to use the `client-side-ts` processor for `.astro` files to get linting of `<script>` tags working properly.
