### ISSUE TITLE
Parsing error: 'return' outside of function

### ISSUE THREAD

**Issue by robertsosinski** [ota-meshi/eslint-plugin-astro#459]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.16.0

### What version of `eslint-plugin-astro` are you using?

1.3.1

### What did you do?

Reopening issue https://github.com/ota-meshi/eslint-plugin-astro/issues/389  as I am seeing this again.

When using `return` in an `.astro` file, I am getting the error:

`Parsing error: 'return' outside of function eslint`

eslint.config.js
```javascript
import pluginAstro from 'eslint-plugin-astro';

export default [
  ...pluginAstro.configs.recommended,
];
```

```astro
---
return Astro.redirect('/path/here');
---

<h1>My Page</h1>
```
See screen snip below:

![Screenshot 2024-12-05 140144](https://github.com/user-attachments/assets/59706573-3e40-44bb-9cda-f4ffe08b1a9d)

### What did you expect to happen?

Not to show this as an error, as I need to return in the astro frontmatter to do things such as `Astro.redirect`.

### What actually happened?

See above, eslint is showing a appropriate return as an error.

### Link to Minimal Reproducible Example

See above.

**Comment by robertsosinski** [comment]
Hey y'all,

Just pinging this issue again, looks like others have the same problem based on the eyes emoji vote.

If there is just some setting that can be configured that anyone knows of, that would be great too.

Thanks!

**Comment by i40west** [comment]
I'm using this:

```javascript
    {
        files: ['**/*.astro'],
        languageOptions: {
            parserOptions: {
                ecmaFeatures: {
                    globalReturn: true,
                },
            },
        },
    },
```

**Comment by robertsosinski** [comment]
Hey @i40west what version of eslint are you using? I'm using 9.25.1 and the `globalReturn` option is not working for me.

Thanks!

**Comment by i40west** [comment]
@robertsosinski I couldn't remember where I found that solution, so I loaded up a project that is also using 9.25.1 (though I've had this in my config for a while). I commented out the `globalReturn` line, and I'm not getting the eslint error anymore even without it. Possible this was addressed?

Anyway, it used to work. You probably have to restart your editor after changing the eslint config.

**Comment by robertsosinski** [comment]
Ok, got this to work now, attaching my `eslint.config.js` file for anyone who would find it useful.

The key thing that made it work for me was putting your config recommendation as a individual config group, not mixing it into another config group. Commenting it out though still makes the error pop up for me, not sure why even as I restarted my computer just to make sure.

```js
import globals from 'globals';
import pluginJs from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import pluginAstro from 'eslint-plugin-astro';

export default [
  {
    ignores: ['dist', 'public'],
  },
  {
    languageOptions: {
      globals: {
        astro: 'writable',
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    files: ['**/*.astro'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          globalReturn: true,
        },
      },
    },
  },
  pluginJs.configs.recommended,
  stylistic.configs.customize({
    semi: true,
    jsx: false,
  }),
  ...pluginAstro.configs.recommended,
];

```
Thanks @i40west for the response as well, really helped me out!

**Comment by virtuallyunknown** [comment]
Getting similar errors here, but unfortunately the solutions proposed here don't work for me.

```js
import {
    eslintBaseConfig,
    eslintPluginStylisticConfig,
    eslintPluginTypescriptConfig,
    eslintPluginUnicornConfig,
    globals,
} from '@virtuallyunknown/eslint-config';

import eslintParserTypeScript from "@typescript-eslint/parser";
import eslintParserAstro from "astro-eslint-parser";
import eslintConfigPrettier from "eslint-config-prettier/flat";
import eslintPluginAstro from 'eslint-plugin-astro';
import eslintPluginBetterTailwindcss from "eslint-plugin-better-tailwindcss";

const eslintPluginBetterTailwindcssConfig = [{
    files: ["**/*.astro"],
    languageOptions: {
        parser: eslintParserAstro,
        parserOptions: {
            // optionally use TypeScript parser within for Astro files
            parser: eslintParserTypeScript
        }
    },
    plugins: {
        "better-tailwindcss": eslintPluginBetterTailwindcss
    },
    rules: {
        // enable all recommended rules to report a warning
        // ...eslintPluginBetterTailwindcss.configs["recommended-warn"].rules,
        // // enable all recommended rules to report an error
        ...eslintPluginBetterTailwindcss.configs["recommended-warn"].rules,

        // // or configure rules individually
        "better-tailwindcss/enforce-consistent-line-wrapping": ["warn", { printWidth: 100, group: 'never', preferSingleLine: true, indent: 4 }],
        "better-tailwindcss/no-unregistered-classes": ["warn", { ignore: ['theme-toggle'] }],
    },
    settings: {
        "better-tailwindcss": {
            // tailwindcss 4: the path to the entry file of the css based tailwind config (eg: `src/global.css`)
            // entryPoint: "src/global.css",
            // tailwindcss 3: the path to the tailwind config file (eg: `tailwind.config.js`)
            tailwindConfig: "./packages/astro/tailwind.config.js"
        }
    }
}]

/** @type {import('@typescript-eslint/utils').TSESLint.FlatConfig.ConfigFile} */
export default [
    {
        languageOptions: {
            globals: {
                astro: 'writable',
                ...globals.browser,
                ...globals.node,
            },
        },
    },
    {
        files: ['**/*.astro'],
        languageOptions: {
            parserOptions: {
                ecmaFeatures: {
                    globalReturn: true,
                },
            },
        },
    },
    ...eslintBaseConfig,
    ...eslintPluginTypescriptConfig,
    ...eslintPluginUnicornConfig,
    ...eslintPluginStylisticConfig,
    ...eslintPluginAstro.configs.recommended,
    ...eslintPluginAstro.configs['jsx-a11y-strict'],
    ...eslintPluginBetterTailwindcssConfig,
    {
        files: ['src/**/*.{ts,tsx}'],
        languageOptions: {
            /**
             * parserOptions.project is optional since it's
             * included in the typescript plugin configuration.
             */
            parserOptions: {
                project: true,
            },
            globals: {
                /**
                 * or other environments
                 */
                ...globals.browser,
            },
        },
        linterOptions: {
            noInlineConfig: false,
            reportUnusedDisableDirectives: true,
        },
    },

    {
        ignores: ['**/*.{js,cjs,mjs}'],
    },
    eslintConfigPrettier,
];
```

Here is the full error log from eslint:

```
[error] 2025-07-05T22:25:55.765Z eslint:eslint Using config loader LegacyConfigLoader
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Calculating config for file /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Searching for eslint.config.js
[error] 2025-07-05T22:25:55.765Z eslint:config-loader [Legacy]: Calculating config for /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.765Z eslint:config-loader [Legacy]: Using config file /home/user/projects/my-project/packages/site/eslint.config.js and base path /home/user/projects/my-project/packages/site
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Calculating config array from config file /home/user/projects/my-project/packages/site/eslint.config.js and base path /home/user/projects/my-project/packages/site
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Loading config file /home/user/projects/my-project/packages/site/eslint.config.js
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Loading config from /home/user/projects/my-project/packages/site/eslint.config.js
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Config file URL is file:///home/user/projects/my-project/packages/site/eslint.config.js
[error] 2025-07-05T22:25:55.765Z eslint:config-loader Config file /home/user/projects/my-project/packages/site/eslint.config.js is not empty
[error] 2025-07-05T22:25:55.770Z eslint:eslint Lint /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.770Z eslint:linter Linting code for /home/user/projects/my-project/packages/site/src/pages/index.astro (pass 1)
[error] 2025-07-05T22:25:55.770Z eslint:linter Verify
[error] 2025-07-05T22:25:55.770Z eslint:linter With flat config: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.770Z eslint:linter Apply the processor: { preprocess: [Function: preprocess], postprocess: [Function: postprocess], supportsAutofix: true, meta: { name: 'astro/client-side-ts', version: '1.3.1' } }
[error] 2025-07-05T22:25:55.770Z eslint:linter A code block was found: '(unnamed)'
[error] 2025-07-05T22:25:55.770Z eslint:languages:js Parsing: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.778Z eslint:languages:js Parsing successful: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.778Z eslint:languages:js Scope analysis: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.778Z eslint:languages:js Scope analysis successful: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.779Z eslint:linter An error occurred while traversing
[error] 2025-07-05T22:25:55.779Z eslint:linter Filename: /home/user/projects/my-project/packages/site/src/pages/index.astro
[error] 2025-07-05T22:25:55.779Z eslint:linter Line: 2
[error] 2025-07-05T22:25:55.779Z eslint:linter Parser Options: {
[error]   ecmaFeatures: { globalReturn: true },
[error]   project: true,
[error]   parser: {
[error]     parse: [Function: parse],
[error]     parseForESLint: [Function: parseForESLint],
[error]     clearCaches: [Function: clearCaches],
[error]     createProgram: [Function: createProgramFromConfigFile],
[error]     withoutProjectParserOptions: [Function: withoutProjectParserOptions],
[error]     version: '8.35.0',
[error]     meta: { name: 'typescript-eslint/parser', version: '8.35.0' }
[error]   },
[error]   extraFileExtensions: [ '.astro' ]
[error] }
[error] 2025-07-05T22:25:55.779Z eslint:linter Settings: {
[error]   'better-tailwindcss': { tailwindConfig: './packages/astro/tailwind.config.js' }
[error] }
[error] An unexpected error occurred:
[error] Error: Non-null Assertion Failed: Expected node to have a parent.
Occurred while linting /home/user/projects/my-project/packages/site/src/pages/index.astro:2
Rule: "@typescript-eslint/no-misused-promises"
    at nullThrows (/home/user/projects/my-project/node_modules/@typescript-eslint/utils/dist/eslint-utils/nullThrows.js:18:15)
    at /home/user/projects/my-project/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises.js:454:46
    at checkReturnStatement (/home/user/projects/my-project/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises.js:455:15)
    at ruleErrorHandler (/home/user/projects/my-project/node_modules/eslint/lib/linter/linter.js:1307:33)
    at /home/user/projects/my-project/node_modules/eslint/lib/linter/source-code-visitor.js:76:46
    at Array.forEach (<anonymous>)
    at SourceCodeVisitor.callSync (/home/user/projects/my-project/node_modules/eslint/lib/linter/source-code-visitor.js:76:30)
    at /home/user/projects/my-project/node_modules/eslint/lib/linter/source-code-traverser.js:291:18
    at Array.forEach (<anonymous>)
    at SourceCodeTraverser.traverseSync (/home/user/projects/my-project/node_modules/eslint/lib/linter/source-code-traverser.js:290:10)
```

Any known workarounds for this?

**Comment by valeriangalliat** [comment]
Encountered this as well after upgrading to pnpm 11 which doesn't hoist automatically all `*eslint*` packages

Happened only in editor and not CLI runs because `node_modules/.bin/eslint` is wrapped with a `NODE_PATH` of all the project dependencies, while editor uses `new ESLint()` APIs without dependency hoisting

eslint-plugin-astro uses `@typescript-eslint/parser` if it can find it, otherwise falls back to Espree - Espree doesn't seem to like the early return in frontmatter while `@typescript-eslint/parser` is OK with it

Docs [say](https://github.com/ota-meshi/eslint-plugin-astro#-installation) need to install explicitly `@typescript-eslint/parser` if we use TypeScript in the frontmatter but seems to apply to if you use early return as well even in plain JS

So fix for me was simply `npm i @typescript-eslint/parser` in my project root

Dumped all the details here https://www.codejam.info/2026/06/astro-eslint-pnpm-11-return-outside-function.html
